name: Build Job

on:
  workflow_call:
    inputs:
      CP_DOCKER_IMG:
        required: true
        type: string
      pr_id:
        required: true
        type: string
      runs_on_arch:
        required: true
        type: string

jobs:
  JOB_Compile:
    name: JOB_Compile
    select: selected_by_default 
    needs: [ ]  
    runs-on: [ 'dedicate-hosted', '${{ inputs.runs_on_arch }}', 'xlarge' ]
    container:
      image: ${{ inputs.CP_DOCKER_IMG }}
      options: --user root
                
    steps: 
      - name: Checkout repository with pre merge
        uses: checkout
        with:
          repository: ${{atomgit.repositoryurl}}
          ref: refs/merge-requests/${{ atomgit.event.number }}/merge

      - name: Execute_shell
        run: |-
            WORKSPACE=${{atomgit.workspace}}
            arch=`uname -m`
            python_3rdparty_path=/opt/buildtools/python-3.11.4/lib/python3.11/site-packages
            source /usr/local/Ascend/ascend-toolkit/set_env.sh
            export PYTHONPATH=${python_3rdparty_path}:$PYTHONPATH
            cd ${WORKSPACE}/build
            sh build.sh

            if [ $(arch) == aarch64 -a -f ${WORKSPACE}/tests/run_UT_test.sh ]; then
                pip list| grep torch
                pip3 install -r ${WORKSPACE}/requirements.txt
                pip3 install coverage

                source /usr/local/Ascend/nnal/atb/set_env.sh
                export PYTORCH_NPU_INSTALL_PATH=${python_3rdparty_path}/torch_npu
                export LD_LIBRARY_PATH=${python_3rdparty_path}/torch_npu/lib:$LD_LIBRARY_PATH
                export LD_LIBRARY_PATH=${python_3rdparty_path}/torch/lib:$LD_LIBRARY_PATH
                export LD_LIBRARY_PATH=${python_3rdparty_path}/torch.libs:$LD_LIBRARY_PATH
                export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/libgomp.so.1:$LD_LIBRARY_PATH
                export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/$(uname -i)-linux/devlib:$LD_LIBRARY_PATH
                export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/$(uname -i)-linux/lib64:$LD_LIBRARY_PATH

                cd ${WORKSPACE}/tests
                sed -i '$d' run_UT_test.sh
                bash run_UT_test.sh 2>&1 |tee build.log
                if  cat build.log|grep OK ; then
                    echo dt succes
                else
                    echo dt failed
                    exit -1
                fi
            fi